### ISSUE TITLE
How get new offsets

### ISSUE THREAD

**Issue by zeroal3nzi** [Sinclairq/discord-hooking#1]
how u get the offest of function like CreateHook etc.. ?

**Comment by Sinclairq** [comment]
It's quite simple. Taking a quick look at the binary of the discord dll (Can be found in your appdata/roaming/discord/0.0.307/modules/discord_hook/) Inside the folder contained there.

Analyzing the DLL as it runs there is 1 function that gets called for applying hooks on the game's DXGI hooks.

If you take a look at the function provided 
(Signature : 48 89 5C 24 ? 57 48 83 EC 20 48 8D 15 ? ? ? ? / RVA : 0x6A5B0 respectively.)
You'll notice very quickly that this is their function which contains many of MinHook's respective functions (MH_ApplyQueued, MH_CreateHook, MH_QueueEnable/DisableHook), based on addresses found in module (dxgi.dll)

You can get the class yourself using the following signature / RVA : 
(Signature : 48 8B 05 ? ? ? ? C3 CC CC CC CC CC CC CC CC 48 89 5C 24 ? /  RVA : 0xA9580)

The SwapChain would be (dxgi.dll + said class) + 0x28. (Note I mean IDXGISwapChain::Present not Present1).

In case you are interested in the rest the offsets are as follow : 
IDXGISwapChain::ResizeBuffers = class + 0x30
IDXGISwapChain::Release = class + 0x34
IDXGISwapChain1::Present1 = class + 0x2C.

Hope this helps out slightly, let me know if you have any followup questions.
